import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import "@/components/base/global.scss";
import "@/components/header/Header.scss";

import "bootstrap/dist/css/bootstrap.min.css";


// import 'bootstrap/dist/js/bootstrap.bundle.min';

// import "@/styles/globals.scss";
// import "@/styles/header.scss";
import Header from "@/components/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" type="image/x-icon" href="/favicon.ico" /> */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        />
      </head>

      <body
      // className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
